### ISSUE TITLE
I can't get this to work on Yosemite

### ISSUE THREAD

**Issue by Madddcow** [vincent-le-normand/Parrot-Status#10]
Hi there.  I can't this to work at all on Yosemite.  I've tried rebooting, reinstalling etc but no luck.  Is anything else required apart from the app itself?

**Comment by verkaz** [comment]
Hi, what is exactly your problem? Please explain it to let us help you.  It works fine for me :-)

**Comment by Madddcow** [comment]
Hi.  The app doesn¹t recognise that my Zik headphones are connectedŠ.but
they definitely ARE connected.  I should mention that I have Zik 2.0 if this
makes a difference.

I¹m running Yosemite 10.10.1 on a MacBook Pro Retina 15².

Cheers
Gary


From:  verkaz <notifications@github.com>
Reply-To:  vincent-le-normand/Parrot-Status
<reply+00a17cac89ffdc8ac5fd70878c8476a08028ef04e81b4c0792cf0000000110d3a8169
2a169ce034293f3@reply.github.com>
Date:  Monday, 19 January 2015 2:57 am
To:  vincent-le-normand/Parrot-Status <Parrot-Status@noreply.github.com>
Cc:  Gary Mulholland <jus_jammin@hotmail.com>
Subject:  Re: [Parrot-Status] I can't get this to work on Yosemite (#10)


Hi, what is exactly your problem? Please explain it to let us help you.  It
works fine for me :-)

‹
Reply to this email directly or view it on GitHub
<https://github.com/vincent-le-normand/Parrot-Status/issues/10#issuecomment-
70415772> .

**Comment by verkaz** [comment]
I guess it actually does a huge difference that your ZIK is 2.0.
The protocols may be completely (or partly) different.  I think you should wait until somebody reverse-engeeneer it..
Good luck

**Comment by Madddcow** [comment]
Ok, thanks for getting back to me.

From:  verkaz <notifications@github.com>
Reply-To:  vincent-le-normand/Parrot-Status
<reply+00a17cac2758b8e843a7172cb766f1898676246d3f7ecf8392cf0000000110d3f4699
2a169ce034293f3@reply.github.com>
Date:  Monday, 19 January 2015 8:23 am
To:  vincent-le-normand/Parrot-Status <Parrot-Status@noreply.github.com>
Cc:  Gary Mulholland <jus_jammin@hotmail.com>
Subject:  Re: [Parrot-Status] I can't get this to work on Yosemite (#10)


I guess it actually does a huge difference that your ZIK is 2.0.
The protocols may be completely (or partly) different.  I think you should
wait until somebody reverse-engeeneer it..
Good luck

‹
Reply to this email directly or view it on GitHub
<https://github.com/vincent-le-normand/Parrot-Status/issues/10#issuecomment-
70429295> .
