### ISSUE TITLE
Append Parrot Zik 2 support

### ISSUE THREAD

**Issue by harobed** [vincent-le-normand/Parrot-Status#12]
Hi,

suggest : append parrot zik 2 support :)

**Comment by k3z** [comment]
+1

**Comment by vincent-le-normand** [comment]
I only have Parrot Zik 1, but thanks to Devmil (https://github.com/twodice/Parrot-Status), Zik 2 support is coming (i'll release a build today)

**Comment by harobed** [comment]
Work great :) Thanks

**Comment by k3z** [comment]
Great work to. 
Just a small issue, when you choose option "Show Battery Percentage Only" the icon disapear in the tray icon bar. After a reboot, the icon was still invisible but the menu was accessible.
Macox Yosemite 10.10.2

**Comment by harobed** [comment]
> Just a small issue, when you choose option "Show Battery Percentage Only" the icon disapear in the 
> tray icon bar. After a reboot, the icon was still invisible but the menu was accessible.
> Macox Yosemite 10.10.2

Issue create here #15
